from assets.text_file import Text_File
from automation.device_connection.device_connection import Device_Connection
from automation.authentication.authentication import single_device_auth,multiple_device_auth